// crud-project-react/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  const [personas, setPersonas] = useState([]);
  const [editingId, setEditingId] = useState(null);
  const [formData, setFormData] = useState({
    dni: '',
    nombres: '',
    apellidos: '',
    fechaNacimiento: '',
    genero: '',
    ciudad: ''
  });
  const [errores, setErrores] = useState({});

  const ciudades = [
    'Quito',
    'Guayaquil',
    'Cuenca',
    'Ambato',
    'Manta',
    'Loja',
    'Riobamba',
    'Machala',
    'Ibarra',
    'Latacunga'
  ];

  const validarCampos = () => {
    const nuevosErrores = {};

    if (!formData.dni.trim()) {
      nuevosErrores.dni = 'El DNI es requerido';
    } else if (!/^\d{10}$/.test(formData.dni)) {
      nuevosErrores.dni = 'El DNI debe tener 10 dígitos';
    } else if (personas.some(p => p.dni === formData.dni && p.id !== editingId)) {
      nuevosErrores.dni = 'El DNI ya existe';
    }

    if (!formData.nombres.trim()) {
      nuevosErrores.nombres = 'Los nombres son requeridos';
    } else if (!/^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s]+$/.test(formData.nombres)) {
      nuevosErrores.nombres = 'Los nombres solo deben contener letras';
    }

    if (!formData.apellidos.trim()) {
      nuevosErrores.apellidos = 'Los apellidos son requeridos';
    } else if (!/^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s]+$/.test(formData.apellidos)) {
      nuevosErrores.apellidos = 'Los apellidos solo deben contener letras';
    }

    if (!formData.fechaNacimiento) {
      nuevosErrores.fechaNacimiento = 'La fecha de nacimiento es requerida';
    } else {
      const fecha = new Date(formData.fechaNacimiento);
      const hoy = new Date();
      if (fecha > hoy) {
        nuevosErrores.fechaNacimiento = 'La fecha no puede ser futura';
      }
    }

    if (!formData.genero) {
      nuevosErrores.genero = 'El género es requerido';
    }

    if (!formData.ciudad) {
      nuevosErrores.ciudad = 'La ciudad es requerida';
    }

    setErrores(nuevosErrores);
    return Object.keys(nuevosErrores).length === 0;
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    if (errores[name]) {
      setErrores(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    if (!validarCampos()) return;

    if (editingId) {
      setPersonas(personas.map(p =>
        p.id === editingId
          ? { ...formData, id: editingId }
          : p
      ));
      setEditingId(null);
    } else {
      const nuevoRegistro = {
        ...formData,
        id: Date.now()
      };
      setPersonas([...personas, nuevoRegistro]);
    }

    setFormData({
      dni: '',
      nombres: '',
      apellidos: '',
      fechaNacimiento: '',
      genero: '',
      ciudad: ''
    });
  };

  const handleEditar = (persona) => {
    setFormData(persona);
    setEditingId(persona.id);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleEliminar = (id) => {
    if (window.confirm('¿Estás seguro de que deseas eliminar este registro?')) {
      setPersonas(personas.filter(p => p.id !== id));
    }
  };

  const handleCancelar = () => {
    setFormData({
      dni: '',
      nombres: '',
      apellidos: '',
      fechaNacimiento: '',
      genero: '',
      ciudad: ''
    });
    setEditingId(null);
    setErrores({});
  };

  return (
    <div className="app-container">
      <div className="app-content">
        <div className="header">
          <h1>Gestión de Personas</h1>
          <p>Formulario completo con validaciones y CRUD</p>
        </div>

        <div className="container">
          {/* Formulario */}
          <div className="form-section">
            <form onSubmit={handleSubmit} className="form-card">
              <h2>{editingId ? 'Editar Persona' : 'Nuevo Registro'}</h2>

              {/* DNI */}
              <div className="form-group">
                <label>DNI *</label>
                <input
                  type="text"
                  name="dni"
                  value={formData.dni}
                  onChange={handleChange}
                  placeholder="1234567890"
                  className={errores.dni ? 'input-error' : ''}
                />
                {errores.dni && <span className="error">{errores.dni}</span>}
              </div>

              {/* Nombres */}
              <div className="form-group">
                <label>Nombres *</label>
                <input
                  type="text"
                  name="nombres"
                  value={formData.nombres}
                  onChange={handleChange}
                  placeholder="Juan Carlos"
                  className={errores.nombres ? 'input-error' : ''}
                />
                {errores.nombres && <span className="error">{errores.nombres}</span>}
              </div>

              {/* Apellidos */}
              <div className="form-group">
                <label>Apellidos *</label>
                <input
                  type="text"
                  name="apellidos"
                  value={formData.apellidos}
                  onChange={handleChange}
                  placeholder="García López"
                  className={errores.apellidos ? 'input-error' : ''}
                />
                {errores.apellidos && <span className="error">{errores.apellidos}</span>}
              </div>

              {/* Fecha de Nacimiento */}
              <div className="form-group">
                <label>Fecha de Nacimiento *</label>
                <input
                  type="date"
                  name="fechaNacimiento"
                  value={formData.fechaNacimiento}
                  onChange={handleChange}
                  className={errores.fechaNacimiento ? 'input-error' : ''}
                />
                {errores.fechaNacimiento && (
                  <span className="error">{errores.fechaNacimiento}</span>
                )}
              </div>

              {/* Género */}
              <div className="form-group">
                <label>Género *</label>
                <div className="radio-group">
                  <div className="radio-item">
                    <input
                      type="radio"
                      id="masculino"
                      name="genero"
                      value="Masculino"
                      checked={formData.genero === 'Masculino'}
                      onChange={handleChange}
                    />
                    <label htmlFor="masculino">Masculino</label>
                  </div>
                  <div className="radio-item">
                    <input
                      type="radio"
                      id="femenino"
                      name="genero"
                      value="Femenino"
                      checked={formData.genero === 'Femenino'}
                      onChange={handleChange}
                    />
                    <label htmlFor="femenino">Femenino</label>
                  </div>
                </div>
                {errores.genero && <span className="error">{errores.genero}</span>}
              </div>

              {/* Ciudad */}
              <div className="form-group">
                <label>Ciudad *</label>
                <select
                  name="ciudad"
                  value={formData.ciudad}
                  onChange={handleChange}
                  className={errores.ciudad ? 'input-error' : ''}
                >
                  <option value="">Seleccione una ciudad</option>
                  {ciudades.map(ciudad => (
                    <option key={ciudad} value={ciudad}>
                      {ciudad}
                    </option>
                  ))}
                </select>
                {errores.ciudad && <span className="error">{errores.ciudad}</span>}
              </div>

              {/* Botones */}
              <div className="button-group">
                <button type="submit" className="btn btn-primary">
                  {editingId ? 'Actualizar' : 'Guardar'}
                </button>
                {editingId && (
                  <button
                    type="button"
                    onClick={handleCancelar}
                    className="btn btn-secondary"
                  >
                    Cancelar
                  </button>
                )}
              </div>
            </form>
          </div>

          {/* Tabla de Registros */}
          <div className="table-section">
            <div className="table-card">
              <h2>Registros ({personas.length})</h2>

              {personas.length === 0 ? (
                <div className="empty-state">
                  <p>No hay registros aún. ¡Crea el primero!</p>
                </div>
              ) : (
                <div className="table-wrapper">
                  <table className="table">
                    <thead>
                      <tr>
                        <th>DNI</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>F. Nacimiento</th>
                        <th>Género</th>
                        <th>Ciudad</th>
                        <th>Acciones</th>
                      </tr>
                    </thead>
                    <tbody>
                      {personas.map(persona => (
                        <tr key={persona.id}>
                          <td>{persona.dni}</td>
                          <td>{persona.nombres}</td>
                          <td>{persona.apellidos}</td>
                          <td>{new Date(persona.fechaNacimiento).toLocaleDateString('es-ES')}</td>
                          <td>{persona.genero}</td>
                          <td>{persona.ciudad}</td>
                          <td>
                            <div className="actions">
                              <button
                                onClick={() => handleEditar(persona)}
                                className="btn-action btn-edit"
                                title="Editar"
                              >
                                ✏️
                              </button>
                              <button
                                onClick={() => handleEliminar(persona.id)}
                                className="btn-action btn-delete"
                                title="Eliminar"
                              >
                                🗑️
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;

// crud-project-vite/src/App.vue
<script setup>
import { ref, computed } from 'vue'

// Estado de la aplicación
const personas = ref([])
const showForm = ref(false)
const editingId = ref(null)

// Formulario
const formData = ref({
  dni: '',
  nombres: '',
  apellidos: '',
  fechaNacimiento: '',
  genero: '',
  ciudad: ''
})

const errors = ref({})

// Ciudades disponibles
const ciudades = [
  'Guayaquil',
  'Quito',
  'Cuenca',
  'Machala',
  'Manta',
  'Portoviejo',
  'Loja',
  'Ambato',
  'Riobamba',
  'Esmeraldas'
]

// Simulación de base de datos en memoria
let nextId = 1

// Validaciones
const validateForm = () => {
  errors.value = {}
  
  // Validar DNI (10 dígitos para Ecuador)
  if (!formData.value.dni.trim()) {
    errors.value.dni = 'El C.I. es requerido'
  } else if (!/^\d{10}$/.test(formData.value.dni)) {
    errors.value.dni = 'El C.I. debe tener 10 dígitos'
  }
  
  // Validar nombres
  if (!formData.value.nombres.trim()) {
    errors.value.nombres = 'Los nombres son requeridos'
  } else if (formData.value.nombres.trim().length < 2) {
    errors.value.nombres = 'Los nombres deben tener al menos 2 caracteres'
  }
  
  // Validar apellidos
  if (!formData.value.apellidos.trim()) {
    errors.value.apellidos = 'Los apellidos son requeridos'
  } else if (formData.value.apellidos.trim().length < 2) {
    errors.value.apellidos = 'Los apellidos deben tener al menos 2 caracteres'
  }
  
  // Validar fecha de nacimiento
  if (!formData.value.fechaNacimiento) {
    errors.value.fechaNacimiento = 'La fecha de nacimiento es requerida'
  } else {
    const fechaNac = new Date(formData.value.fechaNacimiento)
    const hoy = new Date()
    const edad = hoy.getFullYear() - fechaNac.getFullYear()
    if (edad < 0 || edad > 120) {
      errors.value.fechaNacimiento = 'Fecha de nacimiento inválida'
    }
  }
  
  // Validar género
  if (!formData.value.genero) {
    errors.value.genero = 'Debe seleccionar un género'
  }
  
  // Validar ciudad
  if (!formData.value.ciudad) {
    errors.value.ciudad = 'Debe seleccionar una ciudad'
  }
  
  return Object.keys(errors.value).length === 0
}

// CRUD Operations
const createPersona = () => {
  if (!validateForm()) return
  
  const newPersona = {
    id: nextId++,
    ...formData.value
  }
  
  personas.value.push(newPersona)
  resetForm()
  showForm.value = false
}

const updatePersona = () => {
  if (!validateForm()) return
  
  const index = personas.value.findIndex(p => p.id === editingId.value)
  if (index !== -1) {
    personas.value[index] = {
      id: editingId.value,
      ...formData.value
    }
  }
  
  resetForm()
  showForm.value = false
  editingId.value = null
}

const deletePersona = (id) => {
  if (confirm('¿Está seguro de eliminar este registro?')) {
    personas.value = personas.value.filter(p => p.id !== id)
  }
}

const editPersona = (persona) => {
  editingId.value = persona.id
  formData.value = { ...persona }
  showForm.value = true
  errors.value = {}
}

const resetForm = () => {
  formData.value = {
    dni: '',
    nombres: '',
    apellidos: '',
    fechaNacimiento: '',
    genero: '',
    ciudad: ''
  }
  errors.value = {}
  editingId.value = null
}

const handleSubmit = () => {
  if (editingId.value) {
    updatePersona()
  } else {
    createPersona()
  }
}

const cancelForm = () => {
  resetForm()
  showForm.value = false
}

// Calcular edad
const calcularEdad = (fechaNac) => {
  const hoy = new Date()
  const nacimiento = new Date(fechaNac)
  let edad = hoy.getFullYear() - nacimiento.getFullYear()
  const mes = hoy.getMonth() - nacimiento.getMonth()
  if (mes < 0 || (mes === 0 && hoy.getDate() < nacimiento.getDate())) {
    edad--
  }
  return edad
}
</script>

<template>
  <div class="container">
    <header>
      <h1>Sistema de Registro de Usuario</h1>
      <p>UltraNano Soluciones</p>
    </header>

    <div class="actions">
      <button 
        v-if="!showForm" 
        @click="showForm = true" 
        class="btn btn-primary"
      >
        ➕ Nueva Persona
      </button>
    </div>

    <!-- Formulario -->
    <div v-if="showForm" class="form-container">
      <h2>{{ editingId ? 'Editar Persona' : 'Nueva Persona' }}</h2>
      
      <form @submit.prevent="handleSubmit">
        <!-- DNI -->
        <div class="form-group">
          <label for="dni">C.I. (Cédula) *</label>
          <input
            id="dni"
            v-model="formData.dni"
            type="text"
            maxlength="10"
            placeholder="1234567890"
            :class="{ 'error': errors.dni }"
          />
          <span v-if="errors.dni" class="error-message">{{ errors.dni }}</span>
        </div>

        <!-- Nombres -->
        <div class="form-group">
          <label for="nombres">Nombres *</label>
          <input
            id="nombres"
            v-model="formData.nombres"
            type="text"
            placeholder="Juan Carlos"
            :class="{ 'error': errors.nombres }"
          />
          <span v-if="errors.nombres" class="error-message">{{ errors.nombres }}</span>
        </div>

        <!-- Apellidos -->
        <div class="form-group">
          <label for="apellidos">Apellidos *</label>
          <input
            id="apellidos"
            v-model="formData.apellidos"
            type="text"
            placeholder="Pérez García"
            :class="{ 'error': errors.apellidos }"
          />
          <span v-if="errors.apellidos" class="error-message">{{ errors.apellidos }}</span>
        </div>

        <!-- Fecha de Nacimiento -->
        <div class="form-group">
          <label for="fechaNacimiento">Fecha de Nacimiento *</label>
          <input
            id="fechaNacimiento"
            v-model="formData.fechaNacimiento"
            type="date"
            :class="{ 'error': errors.fechaNacimiento }"
          />
          <span v-if="errors.fechaNacimiento" class="error-message">{{ errors.fechaNacimiento }}</span>
        </div>

        <!-- Género -->
        <div class="form-group">
          <label>Género *</label>
          <div class="radio-group">
            <label class="radio-label">
              <input
                type="radio"
                v-model="formData.genero"
                value="Masculino"
              />
              <span>Masculino</span>
            </label>
            <label class="radio-label">
              <input
                type="radio"
                v-model="formData.genero"
                value="Femenino"
              />
              <span>Femenino</span>
            </label>
            <label class="radio-label">
              <input
                type="radio"
                v-model="formData.genero"
                value="Otro"
              />
              <span>Otro</span>
            </label>
          </div>
          <span v-if="errors.genero" class="error-message">{{ errors.genero }}</span>
        </div>

        <!-- Ciudad -->
        <div class="form-group">
          <label for="ciudad">Ciudad *</label>
          <select
            id="ciudad"
            v-model="formData.ciudad"
            :class="{ 'error': errors.ciudad }"
          >
            <option value="">Seleccione una ciudad</option>
            <option v-for="ciudad in ciudades" :key="ciudad" :value="ciudad">
              {{ ciudad }}
            </option>
          </select>
          <span v-if="errors.ciudad" class="error-message">{{ errors.ciudad }}</span>
        </div>

        <!-- Botones -->
        <div class="form-actions">
          <button type="submit" class="btn btn-success">
            {{ editingId ? '💾 Actualizar' : '✅ Guardar' }}
          </button>
          <button type="button" @click="cancelForm" class="btn btn-secondary">
            ❌ Cancelar
          </button>
        </div>
      </form>
    </div>

    <!-- Tabla de datos -->
    <div v-if="personas.length > 0" class="table-container">
      <h2>Registros ({{ personas.length }})</h2>
      <div class="table-responsive">
        <table>
          <thead>
            <tr>
              <th>DNI</th>
              <th>Nombres</th>
              <th>Apellidos</th>
              <th>Edad</th>
              <th>Género</th>
              <th>Ciudad</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="persona in personas" :key="persona.id">
              <td>{{ persona.dni }}</td>
              <td>{{ persona.nombres }}</td>
              <td>{{ persona.apellidos }}</td>
              <td>{{ calcularEdad(persona.fechaNacimiento) }} años</td>
              <td>{{ persona.genero }}</td>
              <td>{{ persona.ciudad }}</td>
              <td class="actions-cell">
                <button
                  @click="editPersona(persona)"
                  class="btn btn-edit"
                  title="Editar"
                >
                  ✏️
                </button>
                <button
                  @click="deletePersona(persona.id)"
                  class="btn btn-delete"
                  title="Eliminar"
                >
                  🗑️
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div v-else-if="!showForm" class="empty-state">
      <p>📋 No hay registros. Haz clic en "Nueva Persona" para comenzar.</p>
    </div>
  </div>
</template>

<style scoped>
.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}

header {
  text-align: center;
  margin-bottom: 30px;
  padding: 20px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 10px;
  color: white;
}

header h1 {
  margin: 0;
  font-size: 2.5em;
}

header p {
  margin: 10px 0 0 0;
  opacity: 0.9;
}

.actions {
  margin-bottom: 20px;
  text-align: center;
}

.form-container {
  background: #2c2c2c;
  padding: 30px;
  border-radius: 10px;
  margin-bottom: 30px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
}

.form-container h2 {
  margin-top: 0;
  color: #667eea;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  margin-bottom: 8px;
  font-weight: 500;
  color: #e0e0e0;
}

.form-group input[type="text"],
.form-group input[type="date"],
.form-group select {
  width: 100%;
  padding: 12px;
  border: 2px solid #444;
  border-radius: 6px;
  font-size: 16px;
  background: #1a1a1a;
  color: #fff;
  transition: border-color 0.3s;
  box-sizing: border-box;
}

.form-group input:focus,
.form-group select:focus {
  outline: none;
  border-color: #667eea;
}

.form-group input.error,
.form-group select.error {
  border-color: #f44336;
}

.error-message {
  display: block;
  color: #f44336;
  font-size: 14px;
  margin-top: 5px;
}

.radio-group {
  display: flex;
  gap: 20px;
  flex-wrap: wrap;
}

.radio-label {
  display: flex;
  align-items: center;
  cursor: pointer;
  padding: 8px 12px;
  border: 2px solid #444;
  border-radius: 6px;
  transition: all 0.3s;
}

.radio-label:hover {
  border-color: #667eea;
}

.radio-label input[type="radio"] {
  margin-right: 8px;
  cursor: pointer;
}

.radio-label span {
  color: #e0e0e0;
}

.form-actions {
  display: flex;
  gap: 10px;
  margin-top: 30px;
}

.btn {
  padding: 12px 24px;
  border: none;
  border-radius: 6px;
  font-size: 16px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s;
  font-family: inherit;
}

.btn-primary {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
}

.btn-success {
  background: #4caf50;
  color: white;
  flex: 1;
}

.btn-success:hover {
  background: #45a049;
}

.btn-secondary {
  background: #666;
  color: white;
  flex: 1;
}

.btn-secondary:hover {
  background: #555;
}

.btn-edit {
  background: #2196f3;
  color: white;
  padding: 8px 12px;
  font-size: 14px;
}

.btn-edit:hover {
  background: #1976d2;
}

.btn-delete {
  background: #f44336;
  color: white;
  padding: 8px 12px;
  font-size: 14px;
}

.btn-delete:hover {
  background: #d32f2f;
}

.table-container {
  background: #2c2c2c;
  padding: 30px;
  border-radius: 10px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
}

.table-container h2 {
  margin-top: 0;
  color: #667eea;
}

.table-responsive {
  overflow-x: auto;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 20px;
}

thead {
  background: #667eea;
  color: white;
}

th, td {
  padding: 12px;
  text-align: left;
  border-bottom: 1px solid #444;
}

th {
  font-weight: 600;
}

tbody tr {
  transition: background-color 0.3s;
}

tbody tr:hover {
  background: #3a3a3a;
}

.actions-cell {
  display: flex;
  gap: 8px;
}

.empty-state {
  text-align: center;
  padding: 60px 20px;
  background: #2c2c2c;
  border-radius: 10px;
  color: #999;
  font-size: 18px;
}

@media (max-width: 768px) {
  .container {
    padding: 10px;
  }

  header h1 {
    font-size: 1.8em;
  }

  .form-container,
  .table-container {
    padding: 20px;
  }

  .form-actions {
    flex-direction: column;
  }

  .radio-group {
    flex-direction: column;
    gap: 10px;
  }

  table {
    font-size: 14px;
  }

  th, td {
    padding: 8px;
  }

  .actions-cell {
    flex-direction: column;
  }
}
</style>
